name: GitHub Actions CI-CD-FLASKTEST

env:
    REPO_NAME: ${{ github.event.repository.name }}
    IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/helloflask:v0.1.0

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ${{ github.workspace }}
        steps:
            - uses: actions/checkout@v3
              
            - uses: docker/login-action@v2
              with:
                    registry: ${{ secrets.ACR_NAME }}.azurecr.io
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_PASSWORD }}
                    ecr: 'false'
                    logout: 'true'
            - run: |
                docker build . -t ${{ env.APP_IMAGE }}
                docker push ${{ env.APP_IMAGE }}