name: GitHub Actions Flask-HelloWorld

env:
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/helloflask:v.0.1.0
  DNS_NAME: helloflasksp-${{ github.run_id }}-${{ github.run_attempt }}

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    outputs:
      should_build: ${{ steps.check_commit.outputs.should_build }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: 'Check Commit Message'
        id: check_commit
        run: |
          echo ::set-output name=should_build::$(if [[ "${{ github.event.head_commit.message }}" == *"deploy"* || "${{ github.event.head_commit.message }}" == *"build"* ]]; then echo "true"; else echo "false"; fi)
    
      - run: |
          if [[ "${{ steps.check_commit.outputs.should_build }}" == "false" ]]; then
            echo "Commit message does not contain 'deploy' or 'build'."
            echo "Skipping build and deploy steps."
            exit 0
          fi
        if: steps.check_commit.outputs.should_build == 'false'

  build:
    runs-on: ubuntu-latest
    needs: push
    outputs:
      should_build: ${{ steps.check_commit_build.outputs.should_build }}
    if: ${{ needs.push.outputs.should_build == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: 'Check Commit Message'
        id: check_commit_build
        run: |
          echo ::set-output name=should_build::$(if [[ "${{ github.event.head_commit.message }}" == *"deploy"* || "${{ github.event.head_commit.message }}" == *"build"* ]]; then echo "true"; else echo "false"; fi)

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          ecr: 'false'
          logout: 'true'
        
      - run: |
          if [[ "${{ steps.check_commit_build.outputs.should_build }}" == "true" ]]; then
            docker build . -t ${{ env.IMAGE_NAME }}
            docker push ${{ env.IMAGE_NAME }}
          fi
        if: steps.check_commit_build.outputs.should_build == 'true'
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.should_build == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: 'Check Commit Message'
        id: check_commit_deploy
        run: |
          echo ::set-output name=should_deploy::$(if [[ "${{ github.event.head_commit.message }}" == *"deploy"* ]]; then echo "true"; else echo "false"; fi)


      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        if: steps.check_commit_deploy.outputs.should_deploy == 'true'

      - name: 'Deploy Container Instance'
        uses: azure/aci-deploy@v1
        with:
          location: ${{ secrets.LOCATION }}
          name: helloflask
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          image: ${{ env.IMAGE_NAME }}
          dns-name-label: ${{ env.DNS_NAME }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: 5000
          cpu: 1
          memory: 1
        if: steps.check_commit_deploy.outputs.should_deploy == 'true'

      - name: 'Logout'
        run: |
          az logout