name: GitHub Actions for Azure

env:
    REPO_CHAT_NAME: ${{ github.event.repository.name }}
    IMAGE_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/helloflask:v.0.1.0
    DNS_NAME: helloflasksp-${{ github.run_id }}-${{ github.run_attempt }}

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    process_commit:
        runs-on: ubuntu-latest
        steps:
            - name: Check Commit Message
              id: check_commit_message
              run: echo "::set-output name=commit_message::${{ github.event.head_commit.message }}"
    
    build:
        needs: process_commit
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(fromJson(needs.process_commit.outputs.commit_message), 'build')
        defaults:
            run:
                shell: bash
                working-directory: ${{ github.workspace }}
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v3

            - name: 'Docker Login'
              uses: docker/login-action@v2
              with:
                registry: ${{ secrets.ACR_NAME }}.azurecr.io
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
                ecr: 'false'
                logout: 'true'
            
            - name: 'Build Docker Image'
              run: |
                docker build . -t ${{ env.IMAGE_NAME }}
                docker push ${{ env.IMAGE_NAME }}

    deploy:
        needs: process_commit
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(fromJson(needs.process_commit.outputs.commit_message), 'deploy')
        defaults:
            run:
                shell: bash
                working-directory: ${{ github.workspace }}
        steps:
            - name: 'Login via Azure CLI'
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: 'Deploy Container Instance'
              uses: azure/aci-deploy@v1
              with:
                location: ${{ secrets.LOCATION }}
                name: helloflask
                resource-group: ${{ secrets.RESOURCE_GROUP }}
                image: ${{ env.IMAGE_NAME }}
                dns-name-label: ${{ env.DNS_NAME }}
                registry-username: ${{ secrets.REGISTRY_USERNAME }}
                registry-password: ${{ secrets.REGISTRY_PASSWORD }}
                ports: 5000
                cpu: 1
                memory: 1

            - name: 'Logout'
              run: |
                az logout